# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_login(object):
    def setupUi(self, form_login):
        form_login.setObjectName("form_login")
        form_login.resize(400, 300)
        form_login.setStyleSheet("background-color: #ffffff;\n"
"")
        self.led_login = QtWidgets.QLineEdit(form_login)
        self.led_login.setGeometry(QtCore.QRect(70, 100, 250, 25))
        self.led_login.setObjectName("led_login")
        self.led_password = QtWidgets.QLineEdit(form_login)
        self.led_password.setGeometry(QtCore.QRect(70, 130, 250, 25))
        self.led_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.led_password.setObjectName("led_password")
        self.user_direction = QtWidgets.QLabel(form_login)
        self.user_direction.setGeometry(QtCore.QRect(70, 70, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.user_direction.setFont(font)
        self.user_direction.setObjectName("user_direction")
        self.btn_login = QtWidgets.QPushButton(form_login)
        self.btn_login.setGeometry(QtCore.QRect(70, 160, 200, 35))
        self.btn_login.setStyleSheet("border: 1px solid;\n"
"border-radius: 12px;\n"
"background-color: #775DF0;\n"
"color: #ffffff;\n"
"")
        self.btn_login.setObjectName("btn_login")

        self.retranslateUi(form_login)
        QtCore.QMetaObject.connectSlotsByName(form_login)

    def retranslateUi(self, form_login):
        _translate = QtCore.QCoreApplication.translate
        form_login.setWindowTitle(_translate("form_login", "Dialog"))
        self.led_login.setPlaceholderText(_translate("form_login", "Логин..."))
        self.led_password.setPlaceholderText(_translate("form_login", "Пароль..."))
        self.user_direction.setText(_translate("form_login", "Введите данные:"))
        self.btn_login.setText(_translate("form_login", "Войти"))
