# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_logon(object):
    def setupUi(self, form_logon):
        form_logon.setObjectName("form_logon")
        form_logon.resize(400, 300)
        form_logon.setStyleSheet("background-color: #ffffff;")
        self.btn_logon = QtWidgets.QPushButton(form_logon)
        self.btn_logon.setGeometry(QtCore.QRect(70, 160, 200, 35))
        self.btn_logon.setStyleSheet("border: 1px solid;\n"
"border-radius: 12px;\n"
"background-color: #775DF0;\n"
"color: #ffffff;\n"
"")
        self.btn_logon.setObjectName("btn_logon")
        self.led_password = QtWidgets.QLineEdit(form_logon)
        self.led_password.setGeometry(QtCore.QRect(70, 100, 250, 25))
        self.led_password.setText("")
        self.led_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.led_password.setObjectName("led_password")
        self.led_login = QtWidgets.QLineEdit(form_logon)
        self.led_login.setGeometry(QtCore.QRect(70, 70, 250, 25))
        self.led_login.setText("")
        self.led_login.setObjectName("led_login")
        self.led_api_key = QtWidgets.QLineEdit(form_logon)
        self.led_api_key.setGeometry(QtCore.QRect(70, 130, 250, 25))
        self.led_api_key.setText("")
        self.led_api_key.setEchoMode(QtWidgets.QLineEdit.Password)
        self.led_api_key.setObjectName("led_api_key")
        self.lbl_prompt_api_key = QtWidgets.QLabel(form_logon)
        self.lbl_prompt_api_key.setGeometry(QtCore.QRect(70, 200, 200, 20))
        self.lbl_prompt_api_key.setOpenExternalLinks(True)
        self.lbl_prompt_api_key.setObjectName("lbl_prompt_api_key")
        self.lbl_user_direction = QtWidgets.QLabel(form_logon)
        self.lbl_user_direction.setGeometry(QtCore.QRect(70, 40, 250, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_user_direction.setFont(font)
        self.lbl_user_direction.setObjectName("lbl_user_direction")

        self.retranslateUi(form_logon)
        QtCore.QMetaObject.connectSlotsByName(form_logon)

    def retranslateUi(self, form_logon):
        _translate = QtCore.QCoreApplication.translate
        form_logon.setWindowTitle(_translate("form_logon", "Dialog"))
        self.btn_logon.setText(_translate("form_logon", "Зарегистрироваться"))
        self.led_password.setPlaceholderText(_translate("form_logon", "Пароль..."))
        self.led_login.setPlaceholderText(_translate("form_logon", "Логин..."))
        self.led_api_key.setPlaceholderText(_translate("form_logon", "Ключ API..."))
        self.lbl_prompt_api_key.setText(_translate("form_logon", "<a href=\"https://www.youtube.com/watch?v=g0P1jAyRaDM\">Как получить ключ API</a>"))
        self.lbl_user_direction.setText(_translate("form_logon", "Ведите свои данные"))
