# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcome_window(object):
    def setupUi(self, welcome_window):
        welcome_window.setObjectName("welcome_window")
        welcome_window.resize(400, 300)
        welcome_window.setStyleSheet("background-color: #ffffff;")
        self.btn_login = QtWidgets.QPushButton(welcome_window)
        self.btn_login.setGeometry(QtCore.QRect(110, 100, 200, 35))
        self.btn_login.setStyleSheet("border: 1px solid;\n"
"border-radius: 12px;\n"
"background-color: #775DF0;\n"
"color: #ffffff;\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.btn_logon = QtWidgets.QPushButton(welcome_window)
        self.btn_logon.setGeometry(QtCore.QRect(110, 140, 200, 35))
        self.btn_logon.setStyleSheet("border: 1px solid;\n"
"border-radius: 12px;\n"
"background-color: #775DF0;\n"
"color: #ffffff;\n"
"")
        self.btn_logon.setObjectName("btn_logon")

        self.retranslateUi(welcome_window)
        QtCore.QMetaObject.connectSlotsByName(welcome_window)

    def retranslateUi(self, welcome_window):
        _translate = QtCore.QCoreApplication.translate
        welcome_window.setWindowTitle(_translate("welcome_window", "Dialog"))
        self.btn_login.setText(_translate("welcome_window", "Войти"))
        self.btn_logon.setText(_translate("welcome_window", "Зарегистрироваться"))
